on:
  pull_request:
    branches:
      - 'main'
    paths:
      - 'contributors/*'

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

    - name: Set up Python
      uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6 # v3.1.2
      with:
        python-version: 3.x

    - name: Clear GITHUB_TOKEN
      run:  export GITHUB_TOKEN=

    - name: Validate Contributor JSON Files
      run: |
        gh auth login
        pip install -r requirements.txt
        python ci/validate.py ${{ github.event.number }}
      env:
        GH_TOKEN: $
